version: "3.9"

services:
  # ------------------ Zookeeper for Kafka ------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mediaverse-net

  # ------------------ Kafka ------------------
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - mediaverse-net

  # ------------------ PostgreSQL ------------------
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mediaverse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mediaverse-net

  # ------------------ MongoDB ------------------
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mediaverse-net

  # ------------------ RabbitMQ ------------------
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mediaverse-net

  # ------------------ AI Doctor Co-Pilot Service ------------------
  ai-doctor-co-pilot-service:
    build:
      context: ./ai-doctor-co-pilot-service
      dockerfile: Dockerfile
    container_name: ai_doctor_co_pilot_service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ai_doctor_co_pilot_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ai_doctor_co_pilot_service
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - mongo
      - postgres
      - kafka
      - rabbitmq
    networks:
      - mediaverse-net

  # ------------------ Example Other Service ------------------
  big-data-research-hub-service:
    build:
      context: ./big-data-research-hub-service
      dockerfile: Dockerfile
    container_name: big_data_research_hub_service
    ports:
      - "8083:8083"
    networks:
      - mediaverse-net

  # ------------------ Appointment Scheduling Service ------------------
  appointment-scheduling-service:
    build:
      context: ./appointment-scheduling-service
      dockerfile: Dockerfile
    container_name: appointment_scheduling_service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mediaverse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - postgres
      - kafka
      - rabbitmq
    networks:
      - mediaverse-net

# Add other services similarly

networks:
  mediaverse-net:
    driver: bridge

volumes:
  postgres-data:
  mongo-data:
