spring:
  application:
    name: ai_doctor_co_pilot_service

  datasource:
    url: jdbc:postgresql://postgres:5432/ai_doctor_co_pilot_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://mongo:27017/ai_doctor_co_pilot_service

  kafka:
    bootstrap-servers: kafka:9092

  rabbitmq:
    host: rabbitmq
    port: 5672

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
