spring:
  application:
    name: appointment_scheduling_service
  data:
    mongodb:
      uri: mongodb://mongo:27017/appointment_scheduling_service
  datasource:
    url: jdbc:postgresql://postgres:5432/appointment_scheduling_service
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka:9092
  rabbitmq:
    host: rabbitmq
    port: 5672

server:
  port: 0  # use random port; override when running locally
management:
  endpoints:
    web:
      exposure:
        include: health,info
